### ISSUE TITLE
Crashes on startup on Servers

### ISSUE THREAD

**Issue by NielsPilgaard** [Snownee/PassableFoliage#1]
Title pretty much - Removing PassableFoliage from the mods folder allowed the server to start.

* Forge Version: 1.15.2-31.1.63
* Mod Version: PassableFoliage-1.15.2-1.0.1
* MixinBootstrap-1.0.3

https://gist.github.com/NillerMedDild/31a17bfd069aef8bf9d927d6699c43a6

**Comment by Snownee** [comment]
Hello. Can you reproduce this with PassableFoliage and MixinBootstrap only?

**Comment by Snownee** [comment]
Nvm, I reproduced
