### ISSUE TITLE
[Suggestion] Remove the icon from mod name

### ISSUE THREAD

**Issue by MarioSMB** [Snownee/PassableFoliage#16]
The little tree icon shown in the mod's name affects sorting of mods in CurseForge, making it harder to find Passable Foliage in the list. Perhaps you could move it to the end of the mod's name?

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/112715108-80099c80-8f19-11eb-8b0c-e929147ddba1.png)
🤔

**Comment by MarioSMB** [comment]
This mostly applies to the CurseForge app (I should have clarified sorry): 
![foliage](https://user-images.githubusercontent.com/1998392/112715609-f4017000-8f2c-11eb-93d6-e3055306b90a.png)

**Comment by Snownee** [comment]
done
