### ISSUE TITLE
Arrows and attacks

### ISSUE THREAD

**Issue by ftzi** [Snownee/PassableFoliage#17]
* Forge Version: 
 * Mod Version: 2.2.1

Hi! Very nice mod. Really improves the game.

I got attacked by some pillagers. They stood on some leaves of a tree, on the ground. Looks like their arrows couldn't pass through the leaves.

Also, I had to destroy the leaves to be able to attack them. Kinda bad, you know? Was an easy and bad fight.

I think arrows and attacks should pass through the leaves. There is the https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass mod for grass. Maybe you can get some info on how he done it for grass.

I also think that the default horizontal speed slow should be slower, but, not a big deal.

Thanks!

**Comment by tikiMC** [comment]
yah this works in 2.2.0, I don't know what changed in this version but it's broken now :(
until this gets fixed i suppose we can just use 2.2.0
