### ISSUE TITLE
Getting stuck.

### ISSUE THREAD

**Issue by staviq** [Snownee/PassableFoliage#2]
* Forge Version: 31.1.63
 * Mod Version: 1.0.1

It's very easy to get stuck in certain situations, and some npcs get stuck too, zombies do not however.

Simple example:
Flat terrain, 1x1x1 hole in the ground, filled with leaves. If you fall/walk in, you cannot get out, jumping does not work.

For players this is just annoying, but for villagers, and mods that possibly add npcs ( minecolonies for example ) this makes them stuck.

Zombies for some reason do not have that problem and will happily take advantage of the situation.

**Comment by Snownee** [comment]
> Flat terrain, 1x1x1 hole in the ground, filled with leaves. If you fall/walk in, you cannot get out, jumping does not work.

I can't reproduce

**Comment by Snownee** [comment]
This has been fixed in 1.0.2
