### ISSUE TITLE
Suffocation in Modded Leaves 

### ISSUE THREAD

**Issue by GamerGaven** [Snownee/PassableFoliage#23]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

1.18.2-4.0.0

### Modloader version

Forge 40.0.19

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Passing through modded leaves like from Biomes O Plenty will cause entities to suffocate. Additionally if players pass through modded leaves a 2d texture of the leaves block is plastered on the screen.

**Comment by DarkkRevenant** [comment]
Yes, I can agree. Only in Biomes O' Plenty however does the 2d textures happen. I tried with BYG.

**Comment by Snownee** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1818
