### ISSUE TITLE
[Request] Add config option to disable leave-mask

### ISSUE THREAD

**Issue by Cursedth** [Snownee/PassableFoliage#24]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

PassableFoliage-1.18.2-forge-4.0.1.jar

### Modloader version

Forge: 40.0.51

### Modpack info

NA

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Did the latest version add a Leave texture (mask) to block players sight when in leaves?
If so, is it, please, possible to add an option in the config file to disable/enable this?
I really like this mod, makes the jungle a jungle, but the extra obscuring is a little too much (and in my opinion unnecessary as the default leaves already obscured sight. Look through 5 blocks of leaves and your ><).

I tried the Beta and to my great delight it wasn't not coded in the Beta yet. 
So, thanks, I am a happy guy. :)

Regards,

**Comment by Snownee** [comment]
There is no such a thing
