### ISSUE TITLE
Passable Stone block issue

### ISSUE THREAD

**Issue by Zwikkry** [Snownee/PassableFoliage#25]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.0.2

### Modloader version

40.1.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/ZnV55WQ7

### Issue description

With the latest update you are able to walk through Stone blocks (you can also hear the leaf rustling noise).

https://user-images.githubusercontent.com/32293196/164690920-bd588c71-0d84-4561-83b8-6467054be6b7.mp4

**Comment by Proxwian** [comment]
Still applicable, not fixed
