### ISSUE TITLE
Ability to walk on leaves while sneaking

### ISSUE THREAD

**Issue by Strubbelkopp** [Snownee/PassableFoliage#28]
### Mod loader

Fabric

### Minecraft version

1.19

### Mod version

5.0.0

### Modloader version

Quilt Loader 0.17.2-beta2 + QSL 2.0.0-beta.9+0.58.0-1.19

### Issue description

It can sometimes be annoying, not to be able to walk on leaves. It would be nice, if there was a config option, that still allows you to walk on leaves while you are sneaking, without the need for an enchantment

**Comment by Snownee** [comment]
no. its behavior is conflict with the enchantment
