### ISSUE TITLE
Transparent Bricks

### ISSUE THREAD

**Issue by Proxwian** [Snownee/PassableFoliage#31]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

PassableFoliage-1.18.2-forge-4.0.4.jar

### Modloader version

Forge 40.1.84

### Modpack info

https://www.curseforge.com/minecraft/modpacks/oxfortpack/

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Still having brick blocks acting like a leaves. With sound and transparent texture when pass through them

**Comment by Snownee** [comment]
what bricks? i can't reproduce it

**Comment by Proxwian** [comment]
Minecraft:bricks block

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/203996418-00db72be-aade-49e3-bc93-b00c248eff07.png)
![image](https://user-images.githubusercontent.com/16059084/203996471-ba0df789-a0a3-495d-8f90-77ab28dc38b7.png)

**Comment by Proxwian** [comment]
Hmm, it looks some of mods in pack make this, cause I no longer can reproduce this only with PF

**Comment by Proxwian** [comment]
No way, you should investigate other mods compatibility

**Comment by Proxwian** [comment]
Without PF bricks not transparent
