### ISSUE TITLE
End's Phantasm Incompatibility

### ISSUE THREAD

**Issue by Proxwian** [Snownee/PassableFoliage#32]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

PassableFoliage-1.18.2-forge-4.0.4.jar

### Modloader version

Forge 40.1.85

### Modpack info

https://www.curseforge.com/minecraft/modpacks/oxfortpack/

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When you have both mods installed, brick blocks acts like leaves (not happens if you have only one of them). Doesn't really sure what's problem it is, so i report both your mod and Ends Phantasm issue pages.

![image](https://user-images.githubusercontent.com/31781674/204122744-d912c05f-96c5-436e-a27f-3883cf97100b.png)

![image](https://user-images.githubusercontent.com/31781674/204122758-9b69a6a1-666b-4590-8c30-e8b5b83b19f6.png)

**Comment by Snownee** [comment]
this is the issue on their end

**Comment by Proxwian** [comment]
Why are you so mean

**Comment by Snownee** [comment]
Why are you so mean? Do you think I have the obligation to have to reproduce your problem? Do you really think I have to investigate your modpack with hundreds of mods, just because a random mcreator mod made a mistake? What did you do for me? What do you expect me to say after checking the source codes of the mod? Grow up, please. Not everyone is existent just for you. This is just ridiculous. 😅

**Comment by Proxwian** [comment]
I spent hours for searching exact mod incompatibility, and you don't even try to do anything

**Comment by Proxwian** [comment]
At least you can suggest me to remove #leaves tag from minecraft bricks block, but you don't. You just close issue

**Comment by Snownee** [comment]
How funny you are. Did you set up a camera in my house? Please tell me and I will remove it. Do you think I am a predictor and already know there is a mod that mistakenly adds leaves tag? Again, your modpack is your own business. be quiet, and stop bargaining.

**Comment by Proxwian** [comment]
I pointed you to EXACT mod incomptibility, again. I just freaking lazy, that's all
