### ISSUE TITLE
mobs sometime just spinning without moving instead pathfinding while touching leaf block

### ISSUE THREAD

**Issue by MilkissWhite** [Snownee/PassableFoliage#35]
### Mod loader

Fabric

### Minecraft version

1.19.3

### Mod version

6.0.0

### Modloader version

Loader : 0.14.15 + API 0.75.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

sorry, I use CurseForge App, and I don't know where is my log file when using this app.

### Issue description

mobs spin. while spin they don't move. only happen when they touching leaf block. not always spin, sometimes they can move normally.

tested golem, villager, zombie, creeper, skeleton. all 5 mob affected.
 
golem = it happens even in attack animation(attacking zombie), or even skeleton shooting him. while spinning, golem can't approch to enemy. most longest time spin.
villager = it happens even in panic(because of zombie). while spinning, villager can't run away. little shorter time spin than golem.
creeper = it happens sometime. but it stops spinning when I fuse him with flint and steel. little longer time spin than zombie.
skenleton = it happens only not fighting. skeleton in combat(aiming target) never spin. in peace state, similar time spin as creeper.
zombie = it happens even chasing villager. switching between move-spin-move-spin shortly. shortest time spin.

config setting here. [modifyPathFinding=false], [alwaysNotViewBlocking=false] both didn't fix this problem.
------
fallDamageReduction = 0.5
fallDamageThreshold = 20
speedReductionHorizontal = 0.3
speedReductionVertical = 0.3
modifyPathFinding = true
playerOnly = false
alwaysNotViewBlocking = true

[modules]
enchantment = false

[sounds]
volume = 1.0
playerOnly = false
-----

**Comment by MarioSMB** [comment]
Happens in 1.20.1 and with custom mobs.

**Comment by Ricenami** [comment]
Happens to me as well

**Comment by Gfamad** [comment]
I can't test right now but I think it's related to the mod "Passable foliage".

**Comment by SettingDust** [comment]
should be fixed with 8.2.0 on fabric. https://modrinth.com/mod/passable-foliage/version/Tv1n5tQ1
Need test

**Comment by SettingDust** [comment]
Close as done. Feel free to reopen if issue still here
