### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aabaddon** [Snownee/PassableFoliage#37]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.19.1-forge-5.0.1.jar

### Modloader version

Forge 1.19.2-forge-43.2.8

### Modpack info

https://pastebin.com/CX6Nkccd

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Instantly crashes with optifine

**Comment by Snownee** [comment]
How do you know it is caused by this mod?
