### ISSUE TITLE
Lagging Server

### ISSUE THREAD

**Issue by Ryinsanity** [Snownee/PassableFoliage#38]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

1.18.2-4.0.4

### Modloader version

Forge 1.18.2 - 40.2.1

### Modpack info

https://www.curseforge.com/minecraft/modpacks/dawn-craft

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

https://spark.lucko.me/zFPb7fdMnm

A certain chunk in the world is lagging the server and the spark report says it's through this mod. I have no other information to help but can answer questions!

**Comment by Snownee** [comment]
hopefully fixed

**Comment by SettingDust** [comment]
~~The fix that released only contains assets~~
MB

It's not passable
