### ISSUE TITLE
[Enhancement] Hide entity from attack target in passable blocks like name tag

### ISSUE THREAD

**Issue by Acat1234** [Snownee/PassableFoliage#39]
### Mod loader

Forge

### Minecraft version

any

### Mod version

any

### Modloader version

any

### Modpack info

not modpack

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

...

### Issue description

I made it a bug report because I wasn't given a choice.
Can it be made so that mobs can't "see" players in leaves it would be neat for like hiding in a bush or something like that, ok? a config would be work for that very well for that sorry if the config already exists for that.

**Comment by SettingDust** [comment]
I think this is out of scope. Should be a standalone mod with API integrated. Not gonna to maintain as a new feature of this mod.
