### ISSUE TITLE
[Feature Request] Climb config

### ISSUE THREAD

**Issue by MrKashew** [Snownee/PassableFoliage#40]
### Mod loader

Forge

### Minecraft version

1.19.3-4

### Mod version

latest

### Modloader version

latest forge 1.19.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Some potential feature requests
- Config to perhaps enable enchantment behavior by default always on (always able to leafwalker)
- New feature: climbable leaves? (able to hold space to ascend like water)
- New feature: climbable tree trunks (either by holding space or like a ladder?)

**Comment by SettingDust** [comment]
I think this is out of scope. Should be a standalone mod with API integrated. Not gonna to maintain as a new feature of this mod.

It's complex logic for what are trunks or leaves that part of a tree. Should be a feature in a climb mod instead of this mod
