### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shenyx110** [Snownee/PassableFoliage#42]
### Mod loader

Forge

### Minecraft version

1.19.4

### Mod version

7.0.1

### Modloader version

forge 45.0.59

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

[minecraft-exported-crash-info-2023-05-19T11-16-09.zip](https://github.com/Snownee/PassableFoliage/files/11513171/minecraft-exported-crash-info-2023-05-19T11-16-09.zip)

**Comment by Snownee** [comment]
why report to me?

**Comment by shenyx110** [comment]
Because it turned out to be normal, but it crashed after adding this mod

**Comment by Snownee** [comment]
are you sure you are sending the correct log? there is even no snow real magic installed in it
