### ISSUE TITLE
[Compatibility] DistantHorizons not rendering leaves 

### ISSUE THREAD

**Issue by facufierro** [Snownee/PassableFoliage#43]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.2.0

### Modloader version

Forge: 40.2.10

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When DistantHorizons is installed passable leaves are not rendered by it.

**Comment by Snownee** [comment]
> in the Distant Horizons configs, change "Block to Avoid" to "none" or "non full"

**Comment by facufierro** [comment]
Thanks!!
