### ISSUE TITLE
[Suggestion] Entity tag for mobs not affected by leaves

### ISSUE THREAD

**Issue by MarioSMB** [Snownee/PassableFoliage#44]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

8.0.0

### Modloader version

Forge 47.1.43

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Some mobs (such as leafcutter ants from Alex's Mobs) are supposed to be able to climb leaves, perhaps there should be an entity tag for mobs that can interact with leaf blocks normally?

**Comment by CaptainKludge** [comment]
I thought it was #Forge:leaf_walker or something. Maybe that was another mod? If it isn't implemented it would be awesome, if it is; where can I find documentation? My packs are still on 1.19.2.

**Comment by Snownee** [comment]
it is `passablefoliage:block`
