### ISSUE TITLE
Suggestion, the same thing for snow layers

### ISSUE THREAD

**Issue by Aceplante** [Snownee/PassableFoliage#45]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

N/A

### Modloader version

N/A

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It has always bothered me that snow layers suddenly become solid as soon as you have 2 or more, allowing you to use them as stairs, so if not a toggle for this mod, a separate new mod?

**Comment by Snownee** [comment]
Hi, you can add the snow block to the block tag: `passablefoliage:passables`

**Comment by Aceplante** [comment]
Unfortunately, when I did that, it affects the entire block not just the hitbox of snow

**Comment by Snownee** [comment]
what do you mean by "the entire block"?

**Comment by Aceplante** [comment]
trying to run and jump through a snow layer still slows you, even when youre not in the hitbox of the snow layer, youll still be slowed anywhere in the block. That makes sense for leaves, but unfortunately not snow, so trying to run through a snowy biome is a nightmare

**Comment by Snownee** [comment]
[PassableFoliage-1.18.2-forge-4.3.0.jar.zip](https://github.com/Snownee/PassableFoliage/files/13260571/PassableFoliage-1.18.2-forge-4.3.0.jar.zip)

I have removed the speed reduction for blocks that do not have the leaves tag. please test it for me.

**Comment by Aceplante** [comment]
Well what im saying is I want the slowness, but only when im actually in the snow layer, not jumping above it. Ill test it soon

Edit: how would I go about using this?

**Comment by Snownee** [comment]
Ah, I see what you mean

**Comment by Snownee** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/passable-foliage/files/4844788
