### ISSUE TITLE
Passable Foliage causing instant leaf decay?

### ISSUE THREAD

**Issue by border999** [Snownee/PassableFoliage#50]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

1.18.2-4.3.0

### Modloader version

40.2.14

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/border999/119376a5406e2b7b14ae3d05a168c689

### Issue description

loaded up a new world after not playing for a long time, updated a number of mods but the only one I can immediately trace as perhaps altering leaf behaviour is passable foliage

**Comment by SettingDust** [comment]
Can you reproduce with only Passable Foliage?

**Comment by border999** [comment]
After extensive testing to find the culprit, it appears that beyond earth is the cultrip for causing all the leaves to decay. I appologize for the wrongful ticket.
