### ISSUE TITLE
Twilight Forest Darkwood Leaves

### ISSUE THREAD

**Issue by vivagabe** [Snownee/PassableFoliage#51]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.2.1

### Modloader version

43.3.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Twilight Forest Darkwood Leaves are not passable. Hopefully an easy fix!

**Comment by SettingDust** [comment]
https://github.com/Snownee/PassableFoliage/blob/1.19-forge/src/main/resources/data/passablefoliage/tags/blocks/passables.json
All blocks that are leaves tag can pass. If it's not leaves tag. I think it should be intended. So, I prefer not add it as default. You can add it to the tag just like the file above with a datapack by yourself

EDIT: According to https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/generated/resources/data/minecraft/tags/blocks/leaves.json#L7. I think it should be passable. Maybe a bug. Can you provide the leave block id?

**Comment by SettingDust** [comment]
Can't reproduce in 1.20.1 and 1.19.3 workspace. Can your reproduce with only the two mods?

**Comment by vivagabe** [comment]
Its strange: if i place the block, i can walk through it. if i encounter the block naturally spawned in the twilight forest, i cannot walk through it.

**Comment by SettingDust** [comment]
They are different blocks. The one you can get by creative is `dark_leaves` that is `#leaves`. The one generated `hardened_dark_leaves` isn't since the author gonna to make it different from the leaves like darker and no decay. So, as I said

> All blocks that are leaves tag can pass. If it's not leaves tag. I think it should be intended. So, I prefer not add it as default. You can add it to the tag just like the file above with a datapack by yourself

**Comment by Snownee** [comment]
just for information: https://github.com/TeamTwilight/twilightforest/issues/1298#issuecomment-927441801
