### ISSUE TITLE
Phasing through brick blocks

### ISSUE THREAD

**Issue by Bohemiangrove666** [Snownee/PassableFoliage#54]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

1.16.5

### Modloader version

Forge 36.2.39

### Modpack info

https://www.curseforge.com/minecraft/modpacks/medieval-mc-forge-mmc1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello! I hope you're having a wonderful day :D

Well, I was building my house when I noticed I could walk through brick blocks, but I could normally walk through brick stairs, brick slabs, etc. At first, I thought it was my server, but I created a single player world and it happened again.

I did some research and apparently I'm not the only one with this issue. I had to go to Luna Pixel Studios Discord to see if it was just me but more players were experiencing the same issue (no collision with brick blocks and phasing through them)

I was wondering if you could kindly help me fix this issue? I tried to look at the mod config file but I really don't know how to do it, I just want to build my house roof but I can't do it because I phase through the brick block :( 

I appreciate the job you do! Thank you :3
![2023-12-14_04 05 18](https://github.com/Snownee/PassableFoliage/assets/105663224/14f5fb1c-c9ea-4a5b-a657-5280a72eb942)
(this one is from another person)
![image_2023-12-14_042453150](https://github.com/Snownee/PassableFoliage/assets/105663224/dcc82ed2-8057-4dd2-9276-f9c1dd9d0274)

**Comment by Snownee** [comment]
what is the mod version?

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by Bohemiangrove666** [comment]
Hi, thank you for answering back! :D

The mod version is Medieval MC [FORGE] 1.16.5 v59 HF - Forge Version 36.2.39. 

I wonder why can't you reproduce it back? Do you know if there's a way to use the config file to prevent this from happening? It just happens to Brick Blocks.

**Comment by Bohemiangrove666** [comment]
Here's the link to the version that is currently installed in my server: https://www.curseforge.com/minecraft/modpacks/medieval-mc-forge-mmc1/files/4650641

I love what you've made with Passable Foliage btw, but I recently started building my house but I keep falling because bricks have no collision for some reason.

**Comment by Snownee** [comment]
That is likely because there is a random mod adding the bricks block to the leaves tag. To find it out, you have to search for it yourself. If you don't know how to do it, contact the modpack developer

**Comment by Bohemiangrove666** [comment]
I searched in the closed Github and apparently it's End's Phantasm. Do you know by any chance how to remove the leaves tag? I'd appreciate it so much, it'd mean a world to me.

**Comment by Bohemiangrove666** [comment]
Also, I tried reporting to Luna Pixel Studios, the ones who created the modpack, and they said I should report to both devs. I honestly didn't want to cause any trouble or bother you.

**Comment by Snownee** [comment]
You can use KubeJS or CraftTweaker to remove the entry
