### ISSUE TITLE
1.20.1 Embeddium Leaves Mixin Conflict 

### ISSUE THREAD

**Issue by Krimatoria** [Snownee/PassableFoliage#57]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

8.2.1

### Modloader version

47.3.5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

https://github.com/Snownee/Kiwi/issues/61 & https://github.com/SrRapero720/EmbeddiumPlus/issues/74

When I disabled your mod and created a new world, I got this.
![image](https://github.com/user-attachments/assets/ffc3db45-ddaa-488d-8e9a-789f11dda4c9)

**Comment by Snownee** [comment]
No log file, and completely unrelated
