### ISSUE TITLE
[suggestion] add enchant that makes them solid again

### ISSUE THREAD

**Issue by ben-mkiv** [Snownee/PassableFoliage#8]
Hi,
this mod might end up in some modpacks and people either like or hate it. 
I would suggest to add an enchant for boots to make the leave blocks walkable again. (and/or a recipe for said enchant, so that its obtainable early game)

**Comment by Snownee** [comment]
Please give an occasion that you need this feature

**Comment by ben-mkiv** [comment]
shearing leaves from top to bottom...

exploring with jumpboost or jetpack and jumping from tree to tree... 

i wouldn't ask if the non solid stuff wouldn't annoy me while playing a 3rd party modpack
