### ISSUE TITLE
Large mushroom caps are considered leaves

### ISSUE THREAD

**Issue by katubug** [Snownee/PassableFoliage#9]
* Forge Version: 31.2.31
 * Mod Version: 1.1.3

Hi! Pretty much what the title says. I am using your mod plus the Enhanced Mushrooms mod, and it seems that caps of large mushrooms are considered leaves. I am not sure whether this is the case without the Enhanced Mushrooms mod, and I am not currently able to test.

Thanks!

**Comment by Snownee** [comment]
Because Enhanced Mushrooms devs think you should consider mushrooms as leaves

**Comment by katubug** [comment]
Ah, okay. That's valid. I apologize for not testing beforehand. Would it be possible to add a config option for users to manually blacklist certain blocks from eligibility? Is that something I should make a separate ticket for?

**Comment by Snownee** [comment]
Enhanced Mushrooms devs have removed the tag in 1.16. I do not know if they will backport the change. But you can do this via a datapack, or change the values of the tag `passablefoliage:passables` by yourself

**Comment by katubug** [comment]
Awesome, thanks very much! I will work something out. I appreciate your
help!
